// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model.event;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mskcc.cbio.fun.model.event.MakePayment;
import org.mskcc.cbio.fun.model.event.MakePaymentDataOnDemand;
import org.mskcc.cbio.fun.model.event.MakePaymentIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MakePaymentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MakePaymentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MakePaymentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MakePaymentIntegrationTest: @Transactional;
    
    @Autowired
    MakePaymentDataOnDemand MakePaymentIntegrationTest.dod;
    
    @Test
    public void MakePaymentIntegrationTest.testCountMakePayments() {
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", dod.getRandomMakePayment());
        long count = MakePayment.countMakePayments();
        Assert.assertTrue("Counter for 'MakePayment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MakePaymentIntegrationTest.testFindMakePayment() {
        MakePayment obj = dod.getRandomMakePayment();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to provide an identifier", id);
        obj = MakePayment.findMakePayment(id);
        Assert.assertNotNull("Find method for 'MakePayment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MakePayment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MakePaymentIntegrationTest.testFindAllMakePayments() {
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", dod.getRandomMakePayment());
        long count = MakePayment.countMakePayments();
        Assert.assertTrue("Too expensive to perform a find all test for 'MakePayment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MakePayment> result = MakePayment.findAllMakePayments();
        Assert.assertNotNull("Find all method for 'MakePayment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MakePayment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MakePaymentIntegrationTest.testFindMakePaymentEntries() {
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", dod.getRandomMakePayment());
        long count = MakePayment.countMakePayments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MakePayment> result = MakePayment.findMakePaymentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MakePayment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MakePayment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MakePaymentIntegrationTest.testFlush() {
        MakePayment obj = dod.getRandomMakePayment();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to provide an identifier", id);
        obj = MakePayment.findMakePayment(id);
        Assert.assertNotNull("Find method for 'MakePayment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMakePayment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MakePayment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MakePaymentIntegrationTest.testMergeUpdate() {
        MakePayment obj = dod.getRandomMakePayment();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to provide an identifier", id);
        obj = MakePayment.findMakePayment(id);
        boolean modified =  dod.modifyMakePayment(obj);
        Integer currentVersion = obj.getVersion();
        MakePayment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MakePayment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MakePaymentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", dod.getRandomMakePayment());
        MakePayment obj = dod.getNewTransientMakePayment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MakePayment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'MakePayment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MakePaymentIntegrationTest.testRemove() {
        MakePayment obj = dod.getRandomMakePayment();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MakePayment' failed to provide an identifier", id);
        obj = MakePayment.findMakePayment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MakePayment' with identifier '" + id + "'", MakePayment.findMakePayment(id));
    }
    
}
