// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model.event;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.mskcc.cbio.fun.model.CoffeeDrinker;
import org.mskcc.cbio.fun.model.CoffeeDrinkerDataOnDemand;
import org.mskcc.cbio.fun.model.event.MakePayment;
import org.mskcc.cbio.fun.model.event.MakePaymentDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MakePaymentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MakePaymentDataOnDemand: @Component;
    
    private Random MakePaymentDataOnDemand.rnd = new SecureRandom();
    
    private List<MakePayment> MakePaymentDataOnDemand.data;
    
    @Autowired
    CoffeeDrinkerDataOnDemand MakePaymentDataOnDemand.coffeeDrinkerDataOnDemand;
    
    public MakePayment MakePaymentDataOnDemand.getNewTransientMakePayment(int index) {
        MakePayment obj = new MakePayment();
        setCoffeeDrinker(obj, index);
        setEventDate(obj, index);
        setPrice(obj, index);
        return obj;
    }
    
    public void MakePaymentDataOnDemand.setCoffeeDrinker(MakePayment obj, int index) {
        CoffeeDrinker coffeeDrinker = coffeeDrinkerDataOnDemand.getRandomCoffeeDrinker();
        obj.setCoffeeDrinker(coffeeDrinker);
    }
    
    public void MakePaymentDataOnDemand.setEventDate(MakePayment obj, int index) {
        Date eventDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEventDate(eventDate);
    }
    
    public void MakePaymentDataOnDemand.setPrice(MakePayment obj, int index) {
        Double price = new Integer(index).doubleValue();
        obj.setPrice(price);
    }
    
    public MakePayment MakePaymentDataOnDemand.getSpecificMakePayment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MakePayment obj = data.get(index);
        Long id = obj.getId();
        return MakePayment.findMakePayment(id);
    }
    
    public MakePayment MakePaymentDataOnDemand.getRandomMakePayment() {
        init();
        MakePayment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MakePayment.findMakePayment(id);
    }
    
    public boolean MakePaymentDataOnDemand.modifyMakePayment(MakePayment obj) {
        return false;
    }
    
    public void MakePaymentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MakePayment.findMakePaymentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MakePayment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MakePayment>();
        for (int i = 0; i < 10; i++) {
            MakePayment obj = getNewTransientMakePayment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
