// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model.event;

import org.mskcc.cbio.fun.model.event.MakePayment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MakePayment_Roo_Configurable {
    
    declare @type: MakePayment: @Configurable;
    
}
