// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mskcc.cbio.fun.model.CoffeeDrinker;
import org.mskcc.cbio.fun.model.CoffeeDrinkerDataOnDemand;
import org.mskcc.cbio.fun.model.CoffeeDrinkerIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CoffeeDrinkerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CoffeeDrinkerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CoffeeDrinkerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CoffeeDrinkerIntegrationTest: @Transactional;
    
    @Autowired
    CoffeeDrinkerDataOnDemand CoffeeDrinkerIntegrationTest.dod;
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testCountCoffeeDrinkers() {
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", dod.getRandomCoffeeDrinker());
        long count = CoffeeDrinker.countCoffeeDrinkers();
        Assert.assertTrue("Counter for 'CoffeeDrinker' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testFindCoffeeDrinker() {
        CoffeeDrinker obj = dod.getRandomCoffeeDrinker();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to provide an identifier", id);
        obj = CoffeeDrinker.findCoffeeDrinker(id);
        Assert.assertNotNull("Find method for 'CoffeeDrinker' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CoffeeDrinker' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testFindAllCoffeeDrinkers() {
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", dod.getRandomCoffeeDrinker());
        long count = CoffeeDrinker.countCoffeeDrinkers();
        Assert.assertTrue("Too expensive to perform a find all test for 'CoffeeDrinker', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CoffeeDrinker> result = CoffeeDrinker.findAllCoffeeDrinkers();
        Assert.assertNotNull("Find all method for 'CoffeeDrinker' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CoffeeDrinker' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testFindCoffeeDrinkerEntries() {
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", dod.getRandomCoffeeDrinker());
        long count = CoffeeDrinker.countCoffeeDrinkers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CoffeeDrinker> result = CoffeeDrinker.findCoffeeDrinkerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CoffeeDrinker' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CoffeeDrinker' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testFlush() {
        CoffeeDrinker obj = dod.getRandomCoffeeDrinker();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to provide an identifier", id);
        obj = CoffeeDrinker.findCoffeeDrinker(id);
        Assert.assertNotNull("Find method for 'CoffeeDrinker' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCoffeeDrinker(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CoffeeDrinker' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testMergeUpdate() {
        CoffeeDrinker obj = dod.getRandomCoffeeDrinker();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to provide an identifier", id);
        obj = CoffeeDrinker.findCoffeeDrinker(id);
        boolean modified =  dod.modifyCoffeeDrinker(obj);
        Integer currentVersion = obj.getVersion();
        CoffeeDrinker merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CoffeeDrinker' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", dod.getRandomCoffeeDrinker());
        CoffeeDrinker obj = dod.getNewTransientCoffeeDrinker(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CoffeeDrinker' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CoffeeDrinker' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CoffeeDrinkerIntegrationTest.testRemove() {
        CoffeeDrinker obj = dod.getRandomCoffeeDrinker();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeDrinker' failed to provide an identifier", id);
        obj = CoffeeDrinker.findCoffeeDrinker(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CoffeeDrinker' with identifier '" + id + "'", CoffeeDrinker.findCoffeeDrinker(id));
    }
    
}
