// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model;

import org.mskcc.cbio.fun.model.CoffeeMachineEventDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CoffeeMachineEventDataOnDemand_Roo_Configurable {
    
    declare @type: CoffeeMachineEventDataOnDemand: @Configurable;
    
}
