// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.mskcc.cbio.fun.model.CoffeeMachineEvent;
import org.mskcc.cbio.fun.model.CoffeeMachineEventDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect CoffeeMachineEventDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CoffeeMachineEventDataOnDemand: @Component;
    
    private Random CoffeeMachineEventDataOnDemand.rnd = new SecureRandom();
    
    private List<CoffeeMachineEvent> CoffeeMachineEventDataOnDemand.data;
    
    public CoffeeMachineEvent CoffeeMachineEventDataOnDemand.getNewTransientCoffeeMachineEvent(int index) {
        CoffeeMachineEvent obj = new CoffeeMachineEvent();
        return obj;
    }
    
    public CoffeeMachineEvent CoffeeMachineEventDataOnDemand.getSpecificCoffeeMachineEvent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CoffeeMachineEvent obj = data.get(index);
        Long id = obj.getId();
        return CoffeeMachineEvent.findCoffeeMachineEvent(id);
    }
    
    public CoffeeMachineEvent CoffeeMachineEventDataOnDemand.getRandomCoffeeMachineEvent() {
        init();
        CoffeeMachineEvent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CoffeeMachineEvent.findCoffeeMachineEvent(id);
    }
    
    public boolean CoffeeMachineEventDataOnDemand.modifyCoffeeMachineEvent(CoffeeMachineEvent obj) {
        return false;
    }
    
    public void CoffeeMachineEventDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CoffeeMachineEvent.findCoffeeMachineEventEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CoffeeMachineEvent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CoffeeMachineEvent>();
        for (int i = 0; i < 10; i++) {
            CoffeeMachineEvent obj = getNewTransientCoffeeMachineEvent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
