// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mskcc.cbio.fun.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mskcc.cbio.fun.model.CoffeeMachineEvent;
import org.mskcc.cbio.fun.model.CoffeeMachineEventDataOnDemand;
import org.mskcc.cbio.fun.model.CoffeeMachineEventIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CoffeeMachineEventIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CoffeeMachineEventIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CoffeeMachineEventIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CoffeeMachineEventIntegrationTest: @Transactional;
    
    @Autowired
    CoffeeMachineEventDataOnDemand CoffeeMachineEventIntegrationTest.dod;
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testCountCoffeeMachineEvents() {
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", dod.getRandomCoffeeMachineEvent());
        long count = CoffeeMachineEvent.countCoffeeMachineEvents();
        Assert.assertTrue("Counter for 'CoffeeMachineEvent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testFindCoffeeMachineEvent() {
        CoffeeMachineEvent obj = dod.getRandomCoffeeMachineEvent();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to provide an identifier", id);
        obj = CoffeeMachineEvent.findCoffeeMachineEvent(id);
        Assert.assertNotNull("Find method for 'CoffeeMachineEvent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CoffeeMachineEvent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testFindAllCoffeeMachineEvents() {
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", dod.getRandomCoffeeMachineEvent());
        long count = CoffeeMachineEvent.countCoffeeMachineEvents();
        Assert.assertTrue("Too expensive to perform a find all test for 'CoffeeMachineEvent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CoffeeMachineEvent> result = CoffeeMachineEvent.findAllCoffeeMachineEvents();
        Assert.assertNotNull("Find all method for 'CoffeeMachineEvent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CoffeeMachineEvent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testFindCoffeeMachineEventEntries() {
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", dod.getRandomCoffeeMachineEvent());
        long count = CoffeeMachineEvent.countCoffeeMachineEvents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CoffeeMachineEvent> result = CoffeeMachineEvent.findCoffeeMachineEventEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CoffeeMachineEvent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CoffeeMachineEvent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testFlush() {
        CoffeeMachineEvent obj = dod.getRandomCoffeeMachineEvent();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to provide an identifier", id);
        obj = CoffeeMachineEvent.findCoffeeMachineEvent(id);
        Assert.assertNotNull("Find method for 'CoffeeMachineEvent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCoffeeMachineEvent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CoffeeMachineEvent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testMergeUpdate() {
        CoffeeMachineEvent obj = dod.getRandomCoffeeMachineEvent();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to provide an identifier", id);
        obj = CoffeeMachineEvent.findCoffeeMachineEvent(id);
        boolean modified =  dod.modifyCoffeeMachineEvent(obj);
        Integer currentVersion = obj.getVersion();
        CoffeeMachineEvent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CoffeeMachineEvent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", dod.getRandomCoffeeMachineEvent());
        CoffeeMachineEvent obj = dod.getNewTransientCoffeeMachineEvent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CoffeeMachineEvent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CoffeeMachineEvent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CoffeeMachineEventIntegrationTest.testRemove() {
        CoffeeMachineEvent obj = dod.getRandomCoffeeMachineEvent();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CoffeeMachineEvent' failed to provide an identifier", id);
        obj = CoffeeMachineEvent.findCoffeeMachineEvent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CoffeeMachineEvent' with identifier '" + id + "'", CoffeeMachineEvent.findCoffeeMachineEvent(id));
    }
    
}
